### ISSUE TITLE
Unable to get it working...

### ISSUE THREAD

**Issue by TheMohitRao** [mancj/SlideUp-Android#17]
Implemented your library on a LinearLayout which contains a third party layout....
But it doesn't work...the slide Right doesnt work. niether the slide Left....
may be I am missing something here...need to implement something else as well ?
I followed the steps you gave for a simple implementation.
What's happening is everything freezes..it neither goes into a hidden state neither it slides..
The third party layout which i am implementing is ArcLayout  from com.ogaclejapan.arclayout.ArcLayout.
Kindly help.

**Comment by mancj** [comment]
Hi. Please, provide your code

**Comment by TheMohitRao** [comment]
Hi, sorry for late response
here is the code:

layoutRightPanel = (RelativeLayout) findViewById(R.id.layout_right_panel);
slideUp = new SlideUp.Builder(layoutRightPanel)
                .withStartState(SlideUp.State.HIDDEN)
                .withStartGravity(Gravity.END)
                .build();


//then on the click of a button :
if (slideUp.isVisible())  slideUp.hide(); else slideUp.show();

 I was trying to implement the slide in from right and slide out on click funcationality

Regards

**Comment by TheMohitRao** [comment]
Also, would like to mention that the panel isnt hidden...still even though i have stated that it should be hidden withStartState(SlideUp.State.HIDDEN)

**Comment by mancj** [comment]
I see no reason for errors. Can you show your xml file?

**Comment by TheMohitRao** [comment]
Hi Mancj, i am sorry to bother you really.... i was able to fix it....it was on my end..i had put my own animation in the view via styles along with the lib........The library works perfectly fine. Thanks for your efforts to make this lib, its awesome. Thank you very much. and sorry to bother you with all this.

Regards

**Comment by mancj** [comment]
no problem, everything is fine.
