### ISSUE TITLE
Bug: in touch event handling when gravity is set to bottom

### ISSUE THREAD

**Issue by YDrall** [mancj/SlideUp-Android#18]
There seems to be a bug in handling touch events when gravity is set to Bottom, means in function #onTouchDownToUp(MotionEvent event). It happens when you touch at bottom of view.
 See:

![slideup_issue_bottomtouch](https://cloud.githubusercontent.com/assets/7512994/23736983/fdc2bde8-04b5-11e7-927c-91aef8327583.gif)

**Comment by mancj** [comment]
Hi. it is working after your changes?

**Comment by YDrall** [comment]
yes, it's working correctly now. or you can test by yourself!

**Comment by mancj** [comment]
Thank you very much!
