### ISSUE TITLE
ٍError Failed to resolve when Add library

### ISSUE THREAD

**Issue by sinadalvand** [mancj/SlideUp-Android#20]
Error:(34, 13) Failed to resolve: com.github.mancj:SlideUp-Android:2.2.2

<a href="openFile:C:/Users/LORD/Desktop/Xin/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

what is this Error?

**Comment by mancj** [comment]
Add the JitPack repository to your build file. Add it in your root build.gradle at the end of repositories:
```
allprojects {
  repositories {
    ...
    maven { url 'https://jitpack.io' }
  }
}
```
