### ISSUE TITLE
Correct dependencies

### ISSUE THREAD

**Issue by augusto-nc** [mancj/SlideUp-Android#23]
I believe that the correct dependencie to be added is this below

dependencies {
	        compile 'com.github.mancj:SlideUp:2.2.2'
}

**Comment by jimit24365** [comment]
Even this is not working

**Comment by mancj** [comment]
I don't understand Your question. Did you add `jipack` to repositories in `build.gradle`?

**Comment by jimit24365** [comment]
Yes i have included jipack to repositories in build.gradle

**Comment by mancj** [comment]
Use ```compile 'com.github.mancj:SlideUp:2.2.1'```

**Comment by jimit24365** [comment]
Still there is same problem.
