### ISSUE TITLE
Error in dependencies

### ISSUE THREAD

**Issue by guilllaumeCritizr** [mancj/SlideUp-Android#24]
Hello !

I've tried to add you library. it looks awesome by the way.
In the documentation you state that the library is tagged 2.2.2, and that we have to add this line:
  - compile 'com.github.mancj:SlideUp-Android:2.2.2'

as well as the maven { url "https://jitpack.io" } in the repositories section.

![capture d ecran 2017-03-31 a 16 25 10](https://cloud.githubusercontent.com/assets/25011331/24554660/a69e99f8-162e-11e7-9dd9-62ea21a75475.png)

This is the error I get, and it goes away if I replace the 2.2.2 version by 2.2.1, it work, so I guess there might be a problem with your uploading of the library ;) 

EDIT: 
It looks like looking at the releases, the 2.2.1 is the last one, so it is a mistake in the readme which states 2.2.2 instead of 2.2.1

Thanks,
Guillaume.

**Comment by jimit24365** [comment]
Still there is the same problem

**Comment by mancj** [comment]
Use version 2.2.1
