### ISSUE TITLE
Issue selecting spinner location

### ISSUE THREAD

**Issue by shaneherd** [mancj/SlideUp-Android#28]
The slide up is working great but I've noticed that in other parts of my app, I can't initialize the selected index of a spinner. The spinner is in an activity which isn't even implementing the SlideUp. I'm performing the following line in an AlertDialog
mySpinner.setSelection(7);

The line executes fine, but then when I tell the AlertDialog to show, the app crashes. I then remove your library and everything works fine. I'm not sure how your library could be causing this, but it seems like it is.

Please let me know if there's any more information you need in order to get this resolved.

**Comment by zTrap** [comment]
@shaneherd Can you show stacktrace?

**Comment by shaneherd** [comment]
[stacktrace.txt](https://github.com/mancj/SlideUp-Android/files/1043513/stacktrace.txt)

This stacktrace is when I went to a page that has a spinner on it that initializes the selected index to something other than zero. The page doesn't have your slide up implemented on it, but before I added the library and after I removed it, everything worked. The app doesn't crash as soon as it sets the selection. It only seems to happen when the page is being drawn. It appears that the app is trying to render the selected item for the spinner and set the text for it. When it tries to do this, there is a null pointer.

This is how I initialize the adapter for the spinner:
SpinnerAdapter adapter = new SpinnerAdapter(context, android.R.layout.simple_spinner_item, source);
adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
spinner.setAdapter(adapter);

**Comment by zTrap** [comment]
@shaneherd In stacktrace I found no words about our library. I guess this crash was invoked by bug in instant run or somthing else. And re-sync project did help. To make sure crash is caused by SlideUp try to add library in dependencies again and if it will repeat let us know

**Comment by shaneherd** [comment]
I'm not using instant run. Also adding the library back in causes the issue
to happen again. Like I said before, the issue happens on a page that
doesn't include your library which is why it's not included in the stack
trace, but removing your library from my project fixes the issue. I really
have no idea how your library is tied to the issue.

**Comment by zTrap** [comment]
@shaneherd Strange magic... Anyway thanks for your feedback
