### ISSUE TITLE
Slide with RecyclerView nested scrolling

### ISSUE THREAD

**Issue by juanpmarin** [mancj/SlideUp-Android#31]
Hi !

I have a recyclerView inside the slide panel view, how can a I get the panel sliding down at the end of the recycler view ? I tried enabling nested scrolling in the recyclerView but it does not work

Sorry for my English, thanks !

**Comment by zTrap** [comment]
Hello, thanks for feedback.

Yes, we have some problems with nested scrolls and clicks. That problems will be resolved in next version.

**Comment by zTrap** [comment]
@juanpmarin Sorry, but `SlideUp` will not support this behaviour, because we move `view` on screen instead scroll. Your view-behaviour is applicable only in scrollable containers

**Comment by vowave** [comment]
funny :)
