### ISSUE TITLE
SlideUp Implementation Issue

### ISSUE THREAD

**Issue by maronrubio** [mancj/SlideUp-Android#32]
Tried to add this on my project but can't seem to get it to work just by following the usage steps described, so I tried to set it up on a new empty project but still not able to make it work.

Imports and everything is in place added it to both fragment and activity but to no avail.

Is there anything that I am missing.

No errors shows up on android monitor.

**Comment by mancj** [comment]
Make sure you added the jitpack repository to your project level build.gradle file.

allprojects {
  repositories {
    ...
    maven { url 'https://jitpack.io' }
  }
}

**Comment by maronrubio** [comment]
My Bad I expected it to behave like a DrawerLayout that you could just slide up from the bottom and it pops up from the usage steps that I followed. Thank you very much
