### ISSUE TITLE
Does slideup use defined apptheme?

### ISSUE THREAD

**Issue by maronrubio** [mancj/SlideUp-Android#35]
Hi, I'm currently using slideup but as I have observed it does not use the defined apptheme even though I already tried to set the theme of the layout xml file.

This happened to me while I was testing my app on API 23, the view is fine on API 26 the checkbox is showing and text. But When I transferred to API 23 the checkbox and text showed are all white. which makes it invisible on a white background.

**Comment by mancj** [comment]
Hi,! No, slide up does not use any themes. Also it doesn't affect your views styles or parameters.

**Comment by maronrubio** [comment]
Thanks, But Is there a way I could set a theme to the layout file that slideup would then inflate using the theme I've set?

**Comment by mancj** [comment]
SlideUp doesn't inflate views, it only cares about slide up/down logic. So you need to customize your themes as usual.
