### ISSUE TITLE
Show top of slideUp, and does onSlide still function?

### ISSUE THREAD

**Issue by minorsecond** [mancj/SlideUp-Android#4]
1) Does `onSlide` still exist? I poked around the code and it looks like it doesn't. I only found `onVisibility` and `onSlideDown`. If it doesn't, how might one change the alpha of the background view according to the slide percentage?

2) is it possible to have a portion of `slideUp` always visible? Essentially, I'd like to have a button on the very top of `slideUp` which displays a name for `slideUp` and, when pressed, calls `slideUp.animateIn();`

Thanks for the awesome implementation of this!

**Comment by mancj** [comment]
1. `onSlide` converted into `onSlideDown` because SlideUp supports just Slide up.

2. No, unfortunately not.
