### ISSUE TITLE
Once slided up, how to get it down? 

### ISSUE THREAD

**Issue by DEV-NEP** [mancj/SlideUp-Android#41]

**Comment by zTrap** [comment]
@DEV-NEP Hello. 
`SlideUp` is not supports listening `TouchEvent`s around of slider view, getted in constructor.

You need to create custom `GestureDetector` and when your gesture are consumed call `slideUp.show()`.

**Comment by DEV-NEP** [comment]
Thanks for the answer

**Comment by zTrap** [comment]
You are welcome :)
