### ISSUE TITLE
Error:Failed to resolve: com.android.support:appcompat-v7:25.4.0

### ISSUE THREAD

**Issue by norbdev** [mancj/SlideUp-Android#43]
I use the stable version of the Android Studio (2.3.3)
And the latest stable appcompat-v7: compile 'com.android.support:appcompat-v7:25.3.1'

In the lib's build.gradle:
>dependencies {
>    compile "com.android.support:support-annotations:${versions.support}"
>    compile "com.android.support:appcompat-v7:${versions.support}"
>}

**Comment by kossstek1234** [comment]
Add those lines to main build.gradle 
```
  repositories {
        maven { url "https://jitpack.io" }
        maven { url "https://maven.google.com" }
    }
```

**Comment by zTrap** [comment]
Starts from v25.4.0 of Support Libraries they based on google maven repository (instead local maven) https://developer.android.com/topic/libraries/support-library/setup.html

**Comment by zTrap** [comment]
Thanks for your issue, I've updated `README.md`
