### ISSUE TITLE
Disabling gesture and loggin doesn't work

### ISSUE THREAD

**Issue by orikl84** [mancj/SlideUp-Android#46]
```
mSlideUp = new SlideUpBuilder(mContactUsView)
                .withStartState(SlideUp.State.HIDDEN)
                .withStartGravity(Gravity.BOTTOM)
                .withGesturesEnabled(false)
                .withLoggingEnabled(true)
                .build();
```

I can still drag the view and I don't see any logs

**Comment by Gounlaf** [comment]
Hi,

                .withLoggingEnabled(true)

Setting it to **false** works.

For the gesture problem, you are right. I think it come from [library/src/main/java/com/mancj/slideup/SlideUp.java#L527](https://github.com/mancj/SlideUp-Android/blob/master/library/src/main/java/com/mancj/slideup/SlideUp.java#L527)
