### ISSUE TITLE
show some slide view part  when hide

### ISSUE THREAD

**Issue by achinverma** [mancj/SlideUp-Android#57]
Hi, i am using this library from bottom to top slide , but when we slide from top to bottom it completely hide the slide view , i want to show some part of the slide view when we slide from top to bottom like in the below screen show. like in the google music app.

![device-2017-12-07-104144](https://user-images.githubusercontent.com/2811593/33699842-9e3d4e3a-db3b-11e7-8568-c3cd02c6331d.png)

**Comment by sohailniazai** [comment]
Hi @achinverma , did you find solution for this ? If yes,  can you share your experience ?

**Comment by achinverma** [comment]
@sohailniazai , you can use bottom navigation sheet in android

**Comment by sohailniazai** [comment]
Actually I need top down slide which is not provided in bottom navigation
sheet. Thanks

**Comment by didiosn** [comment]
Hi @sohailniazai, here it's what I did : 
I've create 2 LinearLayout, the second one will be the slideview, see : 

`<LinearLayout
        android:elevation="5dp"
        android:background="@color/white"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:divider="?android:dividerHorizontal"
        android:showDividers="middle">

<LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:id="@+id/topslideview">

</LinearLayout>
<LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/slideView"
            android:orientation="vertical">

</LinearLayout>
</LinearLayout>
`

So there is TopSlideView and slideview. 

In your activity add : 

`
 slideView = (LinearLayout) findViewById(R.id.slideView);
        topslideview = (LinearLayout) findViewById(R.id.topslideview);
        slideUp = new SlideUpBuilder(slideView)
                .withStartState(SlideUp.State.HIDDEN)
                .withStartGravity(Gravity.BOTTOM)
                .withSlideFromOtherView(topslideview)   
                .build();
`

that's all. Sorry for bad english
