### ISSUE TITLE
withSlideFromOtherView

### ISSUE THREAD

**Issue by lizarazu77** [mancj/SlideUp-Android#59]
i cannot find this methow...

**Comment by sayleep** [comment]
Yeah, same problem. I guess this method was added after the 2.2.7.1 release. So they will have to create a new release which will have all the recent changes.

![image](https://user-images.githubusercontent.com/32460147/34226894-cdc33a2a-e590-11e7-9931-d90753c753f7.png)

**Comment by zTrap** [comment]
added in release 2.2.8
