### ISSUE TITLE
Доработка

### ISSUE THREAD

**Issue by zTrap** [mancj/SlideUp-Android#6]
Либа великолепная, но требует немного доработки. 

1. Изменить `inteface SlideListener` на `class SlideListener` чтобы можно было выбрать только 1 из необходимых методов слушателя.
2. Добавить возможность использовать несколько слушателей.
3. Добавить возможность изменить сторону слайда (сверху - вниз, к примеру)

**Comment by mancj** [comment]
1. Почитай readme. Там написано что любые предложения принимаются.
2. Опиши подробнее, что именно ты хотел бы видеть в библиотеке?

**Comment by zTrap** [comment]
Подробнее уже некуда, только кодом могу подробнее расписать :D

**Comment by mancj** [comment]
Отлично, спасибо. 
Ну, ты можешь расписаь и сделать Pull Request :)
Я буду очень рад

**Comment by zTrap** [comment]
Постараюсь, если хватит сегодня времени :)

**Comment by zTrap** [comment]
Если есть необходимость ещё что добавить, могу доделать

**Comment by mancj** [comment]
Все очень хорошо. Только анимация снизу-вверх работает не очень. 
Посмотри проценты в логах. Начинается с 82 процентов, а заканчивается на -17. Это когда сдвигается сверху. Если смахивать пальцем, то немного лучше, но все равно значения процентов неправильные.

**Comment by zTrap** [comment]
Странно, у меня в логах всё в порядке, ты на чём проверял?

**Comment by zTrap** [comment]
Нашёл проблему, исправил, жди коммит

**Comment by mancj** [comment]
Когда остается примерно 30-40dp, вью будто исчезает

**Comment by mancj** [comment]
сделай pull, я тоже кое что исправил

**Comment by mancj** [comment]
Посмотри затемненный фон, на нем тоже это отражается. Когда резко вверх смахиваешь, он сначала исчезает на несколько миллисекунд, потом снова появляется. Дальше все нормально.

**Comment by zTrap** [comment]
за-pull-ил

**Comment by mancj** [comment]
С процентами удалось разобраться?

**Comment by zTrap** [comment]
Да, вроде

**Comment by mancj** [comment]
Я исправил. Еле заметное подергивание было при автоматическом слайде.

**Comment by mancj** [comment]
Отлично поработали:) Спасибо тебе.
